// AUTO-GENERATED by linux/scripts/gen_drone_profiles.py — do not edit.
// Source: /home/master/spoofer/linux/../RemoteIDSpoofer/drone_profiles.json

#include "drone_profiles.h"

#if defined(LINUX_RIDS)
#include <cstdlib>
#include <cstring>
#else
#include <Arduino.h>
#include <string.h>
#endif

static const char SERIAL_CHARSET[] = "0123456789ABCDEFGHJKLMNPQRSTUVWXYZ";

const DroneProfile DRONE_PROFILES[] = {
    {"DJI", "AVATA", 2, 1, "1581F4QW", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Agras T10", 2, 1, "1581F446", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Agras T100", 2, 1, "1581F8ZL", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Agras T20P", 2, 1, "1581F574", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Agras T25P", 2, 1, "1581F836", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Agras T30", 2, 1, "1581F446", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Agras T40", 2, 1, "1581F574", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Agras T50 & T25", 2, 1, "1581F6BU", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Agras T70P", 2, 1, "1581F8ZX", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Air 2S", 2, 1, "1581F3YT", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Air 3", 2, 1, "1581F6N8", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Air 3S", 2, 1, "1581F895", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Avata 2", 2, 1, "1581F6W8", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Avata 360 (DVN3XT)", 2, 1, "1581FA8J", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "DJI Avata 360 (DVN3NT)", 2, 1, "1581FBLK", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "FPV", 2, 1, "1581F37Q", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "FlyCart 100", 2, 1, "1581FAN4", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "FlyCart 30", 2, 1, "1581F7C6", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Inspire 3", 2, 1, "1581F4Z4", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M30", 2, 1, "1581F4BN", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M30 Dock version", 2, 1, "1581F5BL", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M300 RTK", 2, 1, "1581F1ZN", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M30T", 2, 1, "1581F5BK", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M30T (EU&KR)", 2, 1, "1581F62H", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M30T Dock version", 2, 1, "1581F5BM", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M350 RTK", 2, 1, "1581F6GK", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M3D", 2, 1, "1581F6QA", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M3E", 2, 1, "1581F5FH", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M3M", 2, 1, "1581F5FK", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M3T", 2, 1, "1581F5FJ", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M3TA", 2, 1, "1581FBEX", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "M3TD", 2, 1, "1581F6Q8", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Matrice 400", 2, 1, "1581F8DB", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Matrice 4D", 2, 1, "1581F8HH", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Matrice 4E", 2, 1, "1581F7FV", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Matrice 4T", 2, 1, "1581F7K3", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Matrice 4TD", 2, 1, "1581F8HG", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 2 Enterprise Advanced", 2, 1, "1581F4GC", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 2 Pro", 2, 1, "1581F163", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 2 Zoom", 2, 1, "1581F0M6", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 3", 2, 1, "1581F45T", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 3 Cine", 2, 1, "1581F4QZ", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 3 Classic", 2, 1, "1581F67P", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 3 Pro", 2, 1, "1581F67Q", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 3 Pro Cine", 2, 1, "1581F6MK", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 4 Pro (512 GB)", 2, 1, "1581F986", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic 4 Pro (64 GB)", 2, 1, "1581F8LQ", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic Air 2 (MA2UE1N)", 2, 1, "1581F1WN", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic Air 2 (MA2UE3W)", 2, 1, "1581F3N3", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mavic Pro Platinum", 2, 1, "1581F08Q3", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mini 3", 2, 1, "1581F5YH", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mini 3 Pro", 2, 1, "1581F4XF", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mini 3 Pro", 2, 1, "1581F6L5", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mini 4 Pro", 2, 1, "1581F6Z9", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Mini 5 Pro", 2, 1, "1581F9DE", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Phantom 4 Pro V2.0", 2, 1, "1581F11V", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
    {"DJI", "Phantom 4 RTK", 2, 1, "1581F0UY", 20, 1, 2, 1, "Recreational", "USA", {0x34, 0xD2, 0x62}},
};

const size_t DRONE_PROFILE_COUNT =
    sizeof(DRONE_PROFILES) / sizeof(DRONE_PROFILES[0]);

const DroneProfile *rid_profile_for_index(int drone_index) {
  if (DRONE_PROFILE_COUNT == 0) {
    return nullptr;
  }
  return &DRONE_PROFILES[((drone_index % (int)DRONE_PROFILE_COUNT) + (int)DRONE_PROFILE_COUNT) %
                         (int)DRONE_PROFILE_COUNT];
}

static void random_serial_suffix(char *out, int count) {
  for (int i = 0; i < count; ++i) {
    out[i] = SERIAL_CHARSET[rand() % (sizeof(SERIAL_CHARSET) - 1)];
  }
  out[count] = 0;
}

void rid_generate_serial(const DroneProfile *profile, char *out, size_t out_len) {
  if (!profile || !out || out_len < 2) {
    return;
  }

  memset(out, 0, out_len);
  strncpy(out, profile->serial_prefix, out_len - 1);

  int prefix_len = strlen(out);
  int total = profile->serial_total_len;
  if (total > (int)out_len - 1) {
    total = (int)out_len - 1;
  }
  if (total > prefix_len) {
    random_serial_suffix(out + prefix_len, total - prefix_len);
  }
}

static void generate_faa_operator_id(char *out, size_t out_len) {
  static const char FAA_CHARSET[] = "0123456789ABCDEFGHJKLMNPQRSTUVWXYZ";

  if (out_len < 13) {
    return;
  }

  out[0] = 'F';
  out[1] = 'A';
  for (int i = 2; i < 12; ++i) {
    out[i] = FAA_CHARSET[rand() % (sizeof(FAA_CHARSET) - 1)];
  }
  out[12] = 0;
}

static void generate_eu_operator_id(const DroneProfile *profile, UTM_Utilities *utils,
                                    char *out, size_t out_len) {
  static const char EU_BODY[] = "0123456789abcdefghijklmnopqrstuvwxyz";
  char check_input[20];
  const char *prefix = (profile && profile->eu_op_prefix) ? profile->eu_op_prefix : "DEU";

  if (!utils || out_len < 17) {
    return;
  }

  out[0] = prefix[0];
  out[1] = prefix[1];
  out[2] = prefix[2];

  int j = 0;
  for (int i = 3; i < 15; ++i) {
    out[i] = EU_BODY[rand() % (sizeof(EU_BODY) - 1)];
    check_input[j++] = out[i];
  }

  check_input[j++] = 'X';
  check_input[j++] = '9';
  check_input[j++] = 'k';
  check_input[j] = 0;

  out[15] = utils->luhn36_check(check_input);
  out[16] = 0;
}

static void generate_generic_operator_id(char *out, size_t out_len) {
  static const char CHARSET[] =
      "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

  if (out_len < 17) {
    return;
  }

  for (int i = 0; i < 16; ++i) {
    out[i] = CHARSET[rand() % (sizeof(CHARSET) - 1)];
  }
  out[16] = 0;
}

void rid_generate_operator_id(RidRegion region, const DroneProfile *profile,
                              UTM_Utilities *utils, char *out, size_t out_len) {
  switch (region) {
    case RID_REGION_US_FAA:
      generate_faa_operator_id(out, out_len);
      break;
    case RID_REGION_EU:
      generate_eu_operator_id(profile, utils, out, out_len);
      break;
    default:
      generate_generic_operator_id(out, out_len);
      break;
  }
}

void rid_generate_mac(const DroneProfile *profile, int drone_index, uint8_t mac[6]) {
  if (!profile || !mac) {
    return;
  }

  mac[0] = profile->mac_oui[0] & 0xFC;
  mac[1] = profile->mac_oui[1];
  mac[2] = profile->mac_oui[2];
  mac[3] = static_cast<uint8_t>((drone_index * 37 + rand()) & 0xFF);
  mac[4] = static_cast<uint8_t>(rand() & 0xFF);
  mac[5] = static_cast<uint8_t>(rand() & 0xFF);
}

const char *rid_region_name(RidRegion region) {
  switch (region) {
    case RID_REGION_US_FAA:
      return "US/FAA";
    case RID_REGION_EU:
      return "EU";
    default:
      return "generic";
  }
}
