#!/usr/bin/env python3
"""Generate RemoteIDSpoofer/drone_profiles.cpp from drone_profiles.json."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

CPP_HEADER = """\
// AUTO-GENERATED by linux/scripts/gen_drone_profiles.py — do not edit.
// Source: {source}

#include "drone_profiles.h"

#if defined(LINUX_RIDS)
#include <cstdlib>
#include <cstring>
#else
#include <Arduino.h>
#include <string.h>
#endif

static const char SERIAL_CHARSET[] = "0123456789ABCDEFGHJKLMNPQRSTUVWXYZ";

const DroneProfile DRONE_PROFILES[] = {{
{rows}
}};

const size_t DRONE_PROFILE_COUNT =
    sizeof(DRONE_PROFILES) / sizeof(DRONE_PROFILES[0]);

const DroneProfile *rid_profile_for_index(int drone_index) {{
  if (DRONE_PROFILE_COUNT == 0) {{
    return nullptr;
  }}
  return &DRONE_PROFILES[((drone_index % (int)DRONE_PROFILE_COUNT) + (int)DRONE_PROFILE_COUNT) %
                         (int)DRONE_PROFILE_COUNT];
}}

static void random_serial_suffix(char *out, int count) {{
  for (int i = 0; i < count; ++i) {{
    out[i] = SERIAL_CHARSET[rand() % (sizeof(SERIAL_CHARSET) - 1)];
  }}
  out[count] = 0;
}}

void rid_generate_serial(const DroneProfile *profile, char *out, size_t out_len) {{
  if (!profile || !out || out_len < 2) {{
    return;
  }}

  memset(out, 0, out_len);
  strncpy(out, profile->serial_prefix, out_len - 1);

  int prefix_len = strlen(out);
  int total = profile->serial_total_len;
  if (total > (int)out_len - 1) {{
    total = (int)out_len - 1;
  }}
  if (total > prefix_len) {{
    random_serial_suffix(out + prefix_len, total - prefix_len);
  }}
}}

static void generate_faa_operator_id(char *out, size_t out_len) {{
  static const char FAA_CHARSET[] = "0123456789ABCDEFGHJKLMNPQRSTUVWXYZ";

  if (out_len < 13) {{
    return;
  }}

  out[0] = 'F';
  out[1] = 'A';
  for (int i = 2; i < 12; ++i) {{
    out[i] = FAA_CHARSET[rand() % (sizeof(FAA_CHARSET) - 1)];
  }}
  out[12] = 0;
}}

static void generate_eu_operator_id(const DroneProfile *profile, UTM_Utilities *utils,
                                    char *out, size_t out_len) {{
  static const char EU_BODY[] = "0123456789abcdefghijklmnopqrstuvwxyz";
  char check_input[20];
  const char *prefix = (profile && profile->eu_op_prefix) ? profile->eu_op_prefix : "DEU";

  if (!utils || out_len < 17) {{
    return;
  }}

  out[0] = prefix[0];
  out[1] = prefix[1];
  out[2] = prefix[2];

  int j = 0;
  for (int i = 3; i < 15; ++i) {{
    out[i] = EU_BODY[rand() % (sizeof(EU_BODY) - 1)];
    check_input[j++] = out[i];
  }}

  check_input[j++] = 'X';
  check_input[j++] = '9';
  check_input[j++] = 'k';
  check_input[j] = 0;

  out[15] = utils->luhn36_check(check_input);
  out[16] = 0;
}}

static void generate_generic_operator_id(char *out, size_t out_len) {{
  static const char CHARSET[] =
      "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

  if (out_len < 17) {{
    return;
  }}

  for (int i = 0; i < 16; ++i) {{
    out[i] = CHARSET[rand() % (sizeof(CHARSET) - 1)];
  }}
  out[16] = 0;
}}

void rid_generate_operator_id(RidRegion region, const DroneProfile *profile,
                              UTM_Utilities *utils, char *out, size_t out_len) {{
  switch (region) {{
    case RID_REGION_US_FAA:
      generate_faa_operator_id(out, out_len);
      break;
    case RID_REGION_EU:
      generate_eu_operator_id(profile, utils, out, out_len);
      break;
    default:
      generate_generic_operator_id(out, out_len);
      break;
  }}
}}

void rid_generate_mac(const DroneProfile *profile, int drone_index, uint8_t mac[6]) {{
  if (!profile || !mac) {{
    return;
  }}

  mac[0] = profile->mac_oui[0] & 0xFC;
  mac[1] = profile->mac_oui[1];
  mac[2] = profile->mac_oui[2];
  mac[3] = static_cast<uint8_t>((drone_index * 37 + rand()) & 0xFF);
  mac[4] = static_cast<uint8_t>(rand() & 0xFF);
  mac[5] = static_cast<uint8_t>(rand() & 0xFF);
}}

const char *rid_region_name(RidRegion region) {{
  switch (region) {{
    case RID_REGION_US_FAA:
      return "US/FAA";
    case RID_REGION_EU:
      return "EU";
    default:
      return "generic";
  }}
}}
"""

FALLBACK_OUI = (2, 0, 0)


def c_escape(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def manufacturer_oui_map(profiles: list[dict]) -> dict[str, tuple[int, int, int]]:
    by_mfr: dict[str, Counter[tuple[int, int, int]]] = defaultdict(Counter)
    for profile in profiles:
        oui = profile.get("mac_oui")
        if isinstance(oui, list) and len(oui) == 3:
            by_mfr[profile["manufacturer"]][tuple(int(x) & 0xFF for x in oui)] += 1
    return {mfr: counts.most_common(1)[0][0] for mfr, counts in by_mfr.items()}


def resolve_oui(profile: dict, mfr_oui: dict[str, tuple[int, int, int]]) -> tuple[int, int, int]:
    oui = profile.get("mac_oui")
    if isinstance(oui, list) and len(oui) == 3:
        return tuple(int(x) & 0xFF for x in oui)
    return mfr_oui.get(profile["manufacturer"], FALLBACK_OUI)


def normalize_profile(profile: dict, mfr_oui: dict[str, tuple[int, int, int]]) -> dict:
    manufacturer = str(profile["manufacturer"])
    model = str(profile["model"])
    serial_prefix = str(profile["serial_prefix"])
    serial_total_len = int(profile.get("serial_total_len", len(serial_prefix)))
    ua_type = int(profile.get("ua_type", 2)) & 0xFF
    id_type = int(profile.get("id_type", 1)) & 0xFF
    oui = resolve_oui(profile, mfr_oui)

    return {
        "manufacturer": manufacturer,
        "model": model,
        "ua_type": ua_type,
        "id_type": id_type,
        "serial_prefix": serial_prefix,
        "serial_total_len": serial_total_len,
        "eu_category": int(profile.get("eu_category", 1)) & 0xFF,
        "eu_class": int(profile.get("eu_class", 2)) & 0xFF,
        "classification_region": int(profile.get("classification_region", 1)) & 0xFF,
        "self_id_desc": str(profile.get("self_id_desc", "Recreational")),
        "eu_op_prefix": str(profile.get("eu_op_prefix", "USA")),
        "mac_oui": oui,
    }


def profile_row(profile: dict) -> str:
    oui = profile["mac_oui"]
    return (
        f'    {{"{c_escape(profile["manufacturer"])}", "{c_escape(profile["model"])}", '
        f'{profile["ua_type"]}, {profile["id_type"]}, '
        f'"{c_escape(profile["serial_prefix"])}", {profile["serial_total_len"]}, '
        f'{profile["eu_category"]}, {profile["eu_class"]}, '
        f'{profile["classification_region"]}, '
        f'"{c_escape(profile["self_id_desc"])}", '
        f'"{c_escape(profile["eu_op_prefix"])}", '
        f'{{0x{oui[0]:02X}, 0x{oui[1]:02X}, 0x{oui[2]:02X}}}}},'
    )


def parse_manufacturer_filter(values: list[str] | None) -> set[str] | None:
    if not values:
        return None
    names: set[str] = set()
    for value in values:
        for part in value.split(","):
            part = part.strip()
            if part:
                names.add(part.casefold())
    return names or None


def matches_manufacturer(manufacturer: str, allowed: set[str] | None) -> bool:
    if not allowed:
        return True
    return manufacturer.casefold() in allowed


def load_profiles(path: Path, manufacturers: set[str] | None = None) -> list[dict]:
    with path.open(encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, list):
        raise SystemExit(f"{path}: expected top-level JSON array")
    mfr_oui = manufacturer_oui_map(data)
    profiles = [
        normalize_profile(item, mfr_oui)
        for item in data
        if matches_manufacturer(str(item.get("manufacturer", "")), manufacturers)
    ]
    if manufacturers and not profiles:
        wanted = ", ".join(sorted(manufacturers))
        raise SystemExit(f"{path}: no profiles match manufacturer filter ({wanted})")
    return profiles


def write_cpp(profiles: list[dict], source: Path, output: Path) -> None:
    rows = "\n".join(profile_row(p) for p in profiles)
    content = CPP_HEADER.format(source=source, rows=rows)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")


def print_preview(profiles: list[dict], drone_count: int) -> None:
    if not profiles:
        print("No drone profiles loaded.", file=sys.stderr)
        return
    count = max(1, min(drone_count, 16))
    total = len(profiles)
    print(f"==> Drone profiles: {total} models in pool, broadcasting {count} drone(s)")
    for index in range(count):
        profile = profiles[index % total]
        print(f"    drone {index + 1:2d}: {profile['manufacturer']} {profile['model']}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("json", type=Path, nargs="?", help="drone_profiles.json path")
    parser.add_argument(
        "output",
        type=Path,
        nargs="?",
        help="Output drone_profiles.cpp path",
    )
    parser.add_argument(
        "--list",
        type=int,
        metavar="N",
        help="Print first N drone slot assignments (no code generation)",
    )
    parser.add_argument(
        "--manufacturer",
        action="append",
        metavar="NAME",
        help="Only include profiles for this manufacturer (repeatable or comma-separated)",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[2]
    default_json = root / "RemoteIDSpoofer" / "drone_profiles.json"
    default_cpp = root / "RemoteIDSpoofer" / "drone_profiles.cpp"

    json_path = args.json or default_json
    if not json_path.is_file():
        print(f"Profile JSON not found: {json_path}", file=sys.stderr)
        return 1

    manufacturers = parse_manufacturer_filter(args.manufacturer)
    profiles = load_profiles(json_path, manufacturers)

    if args.list is not None:
        print_preview(profiles, args.list)
        return 0

    output_path = args.output or default_cpp
    write_cpp(profiles, json_path, output_path)
    print(f"Generated {len(profiles)} profiles -> {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
